name: Jockey Trainer Updater

on:
  schedule:
    # Runs daily at 2:00 AM UK time
    - cron: '0 1 * * *'   # 01:00 UTC (covers BST)
    - cron: '0 2 * * *'   # 02:00 UTC (covers GMT)
    # Runs daily at 5:00 AM UK time  
    - cron: '0 4 * * *'   # 04:00 UTC (covers BST)
    - cron: '0 5 * * *'   # 05:00 UTC (covers GMT)
  workflow_dispatch: # Allow manual triggering

jobs:
  update-jockey-trainer-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Add required dependencies
      run: |
        npm install dotenv @supabase/supabase-js
      
    - name: Run jockey trainer analysis
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        RACING_API_USERNAME: ${{ secrets.RACING_API_USERNAME }}
        RACING_API_PASSWORD: ${{ secrets.RACING_API_PASSWORD }}
        TZ: Europe/London
      run: |
        echo "🏇 Starting Daily Jockey Trainer Analysis..."
        echo "Target date: $(date '+%Y-%m-%d')"
        node daily-jockey-trainer-analysis.js
      
    - name: Log completion
      run: |
        echo "✅ Jockey trainer analysis completed at $(date)"
        echo "🕒 Next runs scheduled for 2:00 AM & 5:00 AM UK time" 