name: Master Results Updater

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  update-master-results:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Add dotenv dependency
      run: npm install dotenv
      
    - name: Run master results updater
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        TZ: Europe/London
      run: |
        echo "🏁 Starting Master Results Population..."
        node populate-master-results.js
      
    - name: Log completion
      run: |
        echo "✅ Master results update completed at $(date)"
