name: Update Racecards - NEW OPTIMIZED

on:
  schedule:
    # AGGRESSIVE SCHEDULING to compensate for GitHub delays
    # UK times converted to UTC (UK is GMT+0 winter, GMT+1 summer)
    
    # Initial run at 00:01 UK time (00:01 UTC winter, 23:01 UTC summer)
    - cron: '1 0 * * *'      # 00:01 UTC (00:01 UK winter)
    - cron: '1 23 * * *'     # 23:01 UTC (00:01 UK summer - BST)
    
    # Hourly from 01:00-06:00 UK time  
    - cron: '*/3 0-5 * * *'   # Every 3 minutes 00:00-05:59 UTC (01:00-06:59 UK summer)
    - cron: '*/3 1-6 * * *'   # Every 3 minutes 01:00-06:59 UTC (01:00-06:59 UK winter)
    
    # Every 2 minutes from 07:00-22:00 UK time (racing hours)
    - cron: '*/2 6-21 * * *'  # Every 2 minutes 06:00-21:59 UTC (07:00-22:59 UK summer)  
    - cron: '*/2 7-22 * * *'  # Every 2 minutes 07:00-22:59 UTC (07:00-22:59 UK winter)
    
    # Late evening coverage
    - cron: '*/3 22-23 * * *' # Every 3 minutes 22:00-23:59 UTC
    
  workflow_dispatch: # Allow manual triggering

jobs:
  update-racecards-new:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run NEW OPTIMIZED racecards updater
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        TZ: Europe/London
      run: npm run update-new
      
    - name: Log completion
      run: echo "NEW OPTIMIZED racecards update completed at $(date)" 