name: Update Racecards

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  update-racecards:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run racecards updater
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        TZ: Europe/London
      run: npm run update
      
    - name: Log completion
      run: echo "Racecards update completed at $(date)" 