name: Update Odds Tracking - NEW OPTIMIZED

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  update-odds-tracking-new:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run NEW OPTIMIZED odds tracking
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        TZ: Europe/London
      run: npm run odds-tracking-new
      
    - name: Log completion
      run: echo "NEW OPTIMIZED odds tracking completed at $(date)" 